keys:
  # gpg
  - &admin_konrad F75F59DD45C0D9016CCC3287DE3F236F1516A431
  # personal ssh
  - &admin_konrad_mbp13 age1n2saguuqjaea7szgcy45nuzg0kwh7h9c979wtnf4yt65jv3n4v6qkt37mh
  - &admin_konrad_m3800 age1pcgwdcx2l2hx3j0xrsd3fakxt4qqze6n4xvyl37kkksn63ehyyxqn3utts
  # host ssh
  - &host_m3800 age1s9xeq5c22a9t8escdep5zryz5ug56tsqc9j7wvaw4rkdregue3tqa6c2gz
  - &host_mbp13 age1nyqqwhp6pecz47qmdskagyldlwm69ngu8ec7wyua99lrk28a8pkqaw0dtg
  - &host_rpi4-1 age19xc24qqy5wuham8knmsfaw4ug65k4eqqvsxr7v65q3wem4nkgpxs42g5rf
  - &host_rpi4-2 age1j4rv4r86uj2cqhtwdq0fhcu2hquz670kqp6wjec9hmf6v4t5g55qm55s5g
creation_rules:
  - path_regex: secrets/admins/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *admin_konrad
        age:
          - *admin_konrad_mbp13
          - *admin_konrad_m3800
  - path_regex: secrets/server\.yaml$
    key_groups:
      - pgp:
          - *admin_konrad
        age:
          - *admin_konrad_mbp13
          - *admin_konrad_m3800
          - *host_m3800
          - *host_mbp13

  - path_regex: secrets/wpa_supplicant\.yaml$
    key_groups:
      - pgp:
          - *admin_konrad
        age:
          - *admin_konrad_mbp13
          - *admin_konrad_m3800
          - *host_rpi4-1
          - *host_rpi4-2
