-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
--   פּ ﯟ   some other good icons

return {
    kind = {
        Text = "",
        Method = "m",
        Function = "",
        Constructor = "",
        Field = "",
        Variable = "",
        Class = "",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "",
        Enum = "",
        Keyword = "",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        EnumMember = "",
        Constant = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
    },
    type = {
        Array = "",
        Number = "",
        String = "",
        Boolean = "蘒",
        Object = "",
    },
    documents = {
        File = "",
        Files = "",
        FileContents = "",
        SymlinkFile = "",
        Folder = "",
        OpenFolder = "",
        EmptyFolder = "",
        EmptyOpenFolder = "",
        SymlinkFolder = "",
    },
    git = {
        Add = "",
        Mod = "",
        Remove = "",
        Ignore = "",
        Rename = "",
        Diff = "",
        Repo = "",
        Branch = "",
        Unmerged = "",
        Unstaged = "",
        Staged = "✓",
        Untracked = "★",
        Ignored = "◌",
    },
    ui = {
        Lock = "",
        Circle = "",
        BigCircle = "",
        BigUnfilledCircle = "",
        Square = "",
        Close = "",
        NewFile = "",
        Search = "",
        Lightbulb = "",
        Project = "",
        Dashboard = "",
        History = "",
        Comment = "",
        Bug = "",
        Code = "",
        Telescope = "",
        Gear = "",
        Package = "",
        List = "",
        SignIn = "",
        Check = "",
        Fire = "",
        Note = "",
        BookMark = "",
        Pencil = "",
        ChevronRight = "",
        Table = "",
        Calendar = "",
        Fill00 = "  ", Fill01 = "_ ", Fill02 = "__", Fill03 = "▁▁", Fill04 = "▂▂", Fill05 = "▃▃",
        Fill06 = "▄▄", Fill07 = "▅▅", Fill08 = "▆▆", Fill09 = "▇▇", Fill10 = "██",
    },
    lines = {
        Corner = "└",
        Edge = "│",
    },
    diagnostics = {
        Error = "",
        Warning = "",
        Information = "",
        Question = "",
        Hint = "",
        Attention = "",
    },
    misc = {
        Robot = "ﮧ",
        Squirrel = "",
        Tag = "",
        Watch = "",
    },
}
