local cmd = vim.cmd                          -- execute Vim commands
local fn = vim.fn                            -- call Vim functions
local g = vim.g                              -- global variables
local opt = vim.opt                          -- global/buffer/windows-scoped options

local indent = 4
g.nomodeline=true                            -- disable modelines for security and because we dont need them
if fn.executable("rg") then
    opt.grepprg='rg --vimgrep --no-heading --smart-case'
    opt.grepformat='%f:%l:%c:%m,%f:%l:%m'
end
opt.inccommand='nosplit'                     -- live preview when search/replace
opt.hlsearch=false                           -- :noh by default
opt.lazyredraw = true                        -- faster scrolling
opt.expandtab = true                         -- Use spaces instead of tabs
opt.smartindent=true                         -- Insert indents automatically
opt.autoindent=true                          -- Insert indents automatically
opt.shiftwidth=indent                        -- Size of an indent
opt.tabstop=indent                           -- Number of spaces tabs count for
opt.softtabstop=indent                       -- Number of spaces tabs count for
opt.hidden=true                              -- Enable modified buffers in background
opt.ignorecase=true                          -- Ignore case
opt.joinspaces=false                         -- No double spaces with join after a dot
opt.shiftround=true                          -- Round indent
opt.scrolloff=8                              -- Lines of context
opt.sidescrolloff=8                          -- Columns of context
opt.smartcase=true                           -- Don't ignore case with capitals
opt.splitbelow=true                          -- Put new windows below current
opt.splitright=true                          -- Put new windows right of current
opt.termguicolors=false                      -- True color support (does not work for macos)
opt.wildmode='list:longest'                  -- Command-line completion mode
opt.list=true                                -- Show some invisible characters (tabs...)
opt.number=true                              -- Print line number
opt.relativenumber=true                      -- Relative line numbers
opt.updatetime=50
opt.swapfile=false
opt.backup=false
opt.undofile=true
opt.undodir='/tmp/.vim-undo'
