version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "konradmalik"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
      timezone: "Europe/Warsaw"
    groups:
      flake:
        patterns:
          - "*"
    assignees:
      - "konradmalik"
