- name: install exa from github
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      rustup default stable
      cargo install --git https://github.com/neepoo/exa.git --branch fix-issue-887 --root /usr/local/
    creates: /usr/local/bin/exa

- name: install duf from git releases
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -o duf.deb -L https://github.com/muesli/duf/releases/download/v{{ git_versions.duf }}/duf_{{ git_versions.duf }}_linux_arm64.deb
      dpkg -i duf.deb
      rm -rf duf.deb
    creates: /usr/bin/duf

- name: install up from github
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      git clone --depth 1 https://github.com/akavel/up.git
      cd up
      go build -o /usr/local/bin/up .
    creates: /usr/local/bin/up

- name: install viddy from github
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      git clone --depth 1 --branch v{{ git_versions.viddy }} https://github.com/sachaos/viddy.git
      cd viddy
      go build -o /usr/local/bin/viddy .
    creates: /usr/local/bin/viddy

- name: install gotop arm64 from github
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -L https://github.com/xxxserxxx/gotop/releases/download/v{{ git_versions.gotop }}/gotop_v{{ git_versions.gotop }}_linux_arm64.tgz | tar xvfz -
      mv gotop /usr/local/bin/gotop
    creates: /usr/local/bin/gotop

- name: install ngrok arm64
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm64.tgz
      tar xvf ngrok-stable-linux-arm64.tgz
      mv ./ngrok /usr/local/bin/ngrok
    creates: "/usr/local/bin/ngrok"

- name: install tidy-viewer from github (ubuntu arm64)
  become: yes
  shell:
    chdir: /tmp
    cmd: |
      rustup default stable
      cargo install --git https://github.com/alexhallam/tv.git --tag {{ git_versions.tidy_viewer }} --root /usr/local/
    creates: /usr/local/bin/tidy-viewer
