keys:
  # main
  - &admin_konrad age1p3uhyl5gr00kfykdmhm8tgq75ct2ajcptxqrnrf9hx2nd2w4u5rqmh36k7
  # personal ssh
  - &admin_konrad_ssh age1n2saguuqjaea7szgcy45nuzg0kwh7h9c979wtnf4yt65jv3n4v6qkt37mh
  # host ssh
  - &host_framework age1p8r7cg58ytvv8c4tzdm3eg3rm2x3gu6qu5885r6satxa2jeuyugsn8enh5
  - &host_m3800 age12gvc63kjn266m5tqm9a6f90mwm2such3zhg4q35nf90l5q6e8flqca4h32
  - &host_rpi4-1 age19xc24qqy5wuham8knmsfaw4ug65k4eqqvsxr7v65q3wem4nkgpxs42g5rf
  - &host_rpi4-2 age1j4rv4r86uj2cqhtwdq0fhcu2hquz670kqp6wjec9hmf6v4t5g55qm55s5g
creation_rules:
  - path_regex: hosts/common/users/konrad/secrets\.yaml$
    key_groups:
      - age:
          - *admin_konrad
          - *admin_konrad_ssh
          - *host_framework
          - *host_m3800
          - *host_rpi4-1
          - *host_rpi4-2
  - path_regex: home/konrad/common/secrets\.yaml$
    key_groups:
      - age:
          - *admin_konrad
          - *admin_konrad_ssh
