# https://github.com/kewlfft/ansible-aur
- name: install zsh, plugins and starship using yay
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-completions
      - fzf
      - starship
