- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link zsh and starship config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - zsh
    - starship

- name: change shell to zsh for "{{ target_user }}"
  become: yes
  user:
    name: "{{ target_user }}"
    shell: /bin/zsh
  when: ansible_system == "Linux"

- name: makes sure zfunc exists (sets it up for the later tasks)
  file:
    path: "~/.config/zsh/zfunc"
    state: directory
