- name: install asdf from git
  shell:
    chdir: /tmp
    cmd: |
      git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v{{ git_versions.asdf }} --depth 1
    creates: ~/.asdf

- name: link asdf config
  file:
    src: "{{ repo_path }}/files/{{ item }}"
    path: "~/.{{ item }}"
    state: link
    force: yes
  with_items:
    - asdfrc

- name: create config dir
  file:
    path: ~/.config
    state: directory

- name: make sure config/direnv does not exist
  file:
    path: "~/.config/direnv"
    state: absent

- name: link direnv folder
  file:
    src: "{{ repo_path }}/files/{{ item }}"
    path: "~/.config/{{ item }}"
    state: link
    force: yes
  with_items:
    - direnv

- block:
    - name: Check that the completion file exists
      stat:
        path: "~/.asdf/completions/_asdf"
      register: stat_result

    - name: link asdf completion
      file:
        src: "~/.asdf/completions/_asdf"
        path: "~/.zfunc/_asdf"
        state: link
        force: yes
      when: stat_result.stat.exists

- name: install asdf direnv plugin
  shell:
    chdir: /tmp
    cmd: |
      . ~/.asdf/asdf.sh && \
      asdf plugin-add direnv && \
      asdf install direnv latest && \
      asdf global direnv latest
    creates: ~/.asdf/plugins/direnv

- name: install asdf python plugin
  shell:
    chdir: /tmp
    cmd: |
      . ~/.asdf/asdf.sh && \
      asdf plugin-add python
    creates: ~/.asdf/plugins/python
