- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link broot config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - broot

- name: install broot completion
  shell:
    cmd: |
      curl -o {{ zdotdir }}/zfunc/_broot -L https://dystroy.org/broot/download/completion/_broot
    creates: "{{ zdotdir }}/zfunc/_broot"

- name: install br completion
  shell:
    cmd: |
      curl -o {{ zdotdir }}/zfunc/_br -L https://dystroy.org/broot/download/completion/_br
    creates: "{{ zdotdir }}/zfunc/_br"

- name: install br zsh function
  shell:
    cmd: |
      broot --print-shell-function zsh > {{ zdotdir }}/zfunc/br
    creates: "{{ zdotdir }}/zfunc/br"
