- include: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- include: osx.yaml
  when: ansible_distribution == "MacOSX"

- include: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link broot config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - broot

- name: install broot completion
  shell:
    cmd: |
      curl -o ~/.zfunc/_broot -L https://dystroy.org/broot/download/completion/_broot
    creates: ~/.zfunc/_broot

- name: install br completion
  shell:
    cmd: |
      curl -o ~/.zfunc/_br -L https://dystroy.org/broot/download/completion/_br
    creates: ~/.zfunc/_br

- name: install br zsh function
  shell:
    cmd: |
      broot --print-shell-function zsh > ~/.zfunc/br
    creates: ~/.zfunc/_br
