- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: set default toolchain
  args:
    executable: /bin/bash
  environment:
    PATH: "~/.cargo/bin:{{ ansible_env.PATH }}"
  shell:
    cmd: |
      rustup install stable && \
      rustup default stable
