require('config.telescope')
require('config.treesitter')
require('config.colorscheme')
require('config.completion')
require('config.fugitive')
require('config.lualine')
require('config.buftabline')
require('config.lsp')
