require('user.settings')
require('user.keymaps')
require('user.plugins')

require('user.autopairs')
require('user.colorscheme')
require('user.comment')
require('user.cmp')
require('user.distant')
require('user.fugitive')
require('user.gitsigns')
require('user.harpoon')
require('user.lsp')
require('user.lualine')
require('user.nvim-tree')
require('user.telescope')
require('user.treesitter')
require('user.which-key')

require('user.autocommands')
