{
  wayland.windowManager.hyprland.settings = {
    # Mouse bindings
    bindm = [
      "SUPER,mouse:272,movewindow"
      "SUPER,mouse:273,resizewindow"
    ];
    bindel = [
      ",XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
      ",XF86MonBrightnessUp, exec, light -A 10"
      ",XF86MonBrightnessDown, exec, light -U 10"
    ];
    bindl = [
      ",XF86AudioNext,exec,playerctl next"
      ",XF86AudioPause,exec,playerctl play-pause"
      ",XF86AudioPlay,exec,playerctl play-pause"
      ",XF86AudioPrev,exec,playerctl previous"
      ",XF86AudioStop,exec,playerctl stop"
    ];
    bind = [
      # Keyboard alt behavior
      "SUPER,c,exec,hyprctl keyword input:kb_options grp:shifts_toggle,ctrl:nocaps,lv3:lalt_switch"
      "SUPERSHIFT,c,exec,hyprctl keyword input:kb_options grp:shifts_toggle,ctrl:nocaps"

      # Program bindings
      "SUPER,return,exec,$TERMINAL"
      "SUPER,w,exec,makoctl dismiss"
      "SUPER,b,exec,$BROWSER"
      "SUPER,space,exec,wofi --show drun --sort-order=alphabetical"

      # Screenshots
      "SUPER,p,exec,hyprshot --mode region --output /tmp"
      "SUPERSHIFT,p,exec,hyprshot --freeze --mode region --output /tmp"

      # Window manager controls
      "SUPERSHIFT,q,killactive"
      "SUPERSHIFT,e,exit"
      "SUPER,f,fullscreen,1"
      "SUPERSHIFT,f,fullscreen,0"
      "SUPERSHIFT,space,togglefloating"
      "SUPER,minus,splitratio,-0.25"
      "SUPERSHIFT,minus,splitratio,-0.3333333"
      "SUPER,equal,splitratio,0.25"
      "SUPERSHIFT,equal,splitratio,0.3333333"

      # dwindle
      "SUPER,s,pseudo"
      "SUPER,g,togglegroup"
      "SUPER,apostrophe,changegroupactive,f"
      "SUPERSHIFT,apostrophe,changegroupactive,b"

      # rest
      "SUPER,left,movefocus,l"
      "SUPER,right,movefocus,r"
      "SUPER,up,movefocus,u"
      "SUPER,down,movefocus,d"
      "SUPER,h,movefocus,l"
      "SUPER,l,movefocus,r"
      "SUPER,k,movefocus,u"
      "SUPER,j,movefocus,d"
      "SUPERSHIFT,left,movewindow,l"
      "SUPERSHIFT,right,movewindow,r"
      "SUPERSHIFT,up,movewindow,u"
      "SUPERSHIFT,down,movewindow,d"
      "SUPERSHIFT,h,movewindow,l"
      "SUPERSHIFT,l,movewindow,r"
      "SUPERSHIFT,k,movewindow,u"
      "SUPERSHIFT,j,movewindow,d"
      "SUPERSHIFT,j,movewindow,d"
      "SUPER,tab,cyclenext"
      "SUPERSHIFT,tab,cyclenext,prev"
      "SUPERCONTROL,tab,swapnext"
      "SUPERCONTROLSHIFT,tab,swapnext,prev"
      "SUPERCONTROL,left,focusmonitor,l"
      "SUPERCONTROL,right,focusmonitor,r"
      "SUPERCONTROL,up,focusmonitor,u"
      "SUPERCONTROL,down,focusmonitor,d"
      "SUPERCONTROL,h,focusmonitor,l"
      "SUPERCONTROL,l,focusmonitor,r"
      "SUPERCONTROL,k,focusmonitor,u"
      "SUPERCONTROL,j,focusmonitor,d"
      "SUPERCONTROLSHIFT,left,movewindow,mon:l"
      "SUPERCONTROLSHIFT,right,movewindow,mon:r"
      "SUPERCONTROLSHIFT,up,movewindow,mon:u"
      "SUPERCONTROLSHIFT,down,movewindow,mon:d"
      "SUPERCONTROLSHIFT,h,movewindow,mon:l"
      "SUPERCONTROLSHIFT,l,movewindow,mon:r"
      "SUPERCONTROLSHIFT,k,movewindow,mon:u"
      "SUPERCONTROLSHIFT,j,movewindow,mon:d"
      "SUPERALT,left,movecurrentworkspacetomonitor,l"
      "SUPERALT,right,movecurrentworkspacetomonitor,r"
      "SUPERALT,up,movecurrentworkspacetomonitor,u"
      "SUPERALT,down,movecurrentworkspacetomonitor,d"
      "SUPERALT,h,movecurrentworkspacetomonitor,l"
      "SUPERALT,l,movecurrentworkspacetomonitor,r"
      "SUPERALT,k,movecurrentworkspacetomonitor,u"
      "SUPERALT,j,movecurrentworkspacetomonitor,d"
      "SUPER,u,togglespecialworkspace"
      "SUPERSHIFT,u,movetoworkspace,special"
      "SUPER,1,workspace,01"
      "SUPER,2,workspace,02"
      "SUPER,3,workspace,03"
      "SUPER,4,workspace,04"
      "SUPER,5,workspace,05"
      "SUPER,6,workspace,06"
      "SUPER,7,workspace,07"
      "SUPER,8,workspace,08"
      "SUPER,9,workspace,09"
      "SUPER,0,workspace,10"
      "SUPERSHIFT,1,movetoworkspacesilent,01"
      "SUPERSHIFT,2,movetoworkspacesilent,02"
      "SUPERSHIFT,3,movetoworkspacesilent,03"
      "SUPERSHIFT,4,movetoworkspacesilent,04"
      "SUPERSHIFT,5,movetoworkspacesilent,05"
      "SUPERSHIFT,6,movetoworkspacesilent,06"
      "SUPERSHIFT,7,movetoworkspacesilent,07"
      "SUPERSHIFT,8,movetoworkspacesilent,08"
      "SUPERSHIFT,9,movetoworkspacesilent,09"
      "SUPERSHIFT,0,movetoworkspacesilent,10"
    ];
  };
}
