{
  stylix,
  lib,
  writeTextDir,
}:
let
  indent = string: "    " + lib.concatStringsSep "\n    " (lib.splitString "\n" string);
in
writeTextDir "stylix.lua" (
  lib.concatLines [
    # lua
    ''
      -- Generated by Stylix
      local wezterm = require("wezterm")
      local stylix = {
    ''
    (indent stylix.targets.wezterm.luaBody)
    # lua
    ''
      }
    ''
    # lua
    ''
      return {
        setup = function(config)
          for key, value in pairs(stylix) do
              config[key] = value
          end
        end
      }
    ''
  ]
)
