- name: fonts tinygo tap
  community.general.homebrew_tap:
    name:
      - tinygo-org/tools

- name: install go brew packages
  community.general.homebrew:
    name:
      - go
      - tinygo
    update_homebrew: yes
