- name: create config dir (so that it is not linked)
  file:
    path: ~/.config
    state: directory

- name: link general dot files
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - inputrc
    - gdb

- name: link no folding general dot files
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" --no-folding {{ item }}
  with_items:
    - gpg

