- name: install python compile-dependencies
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - base-devel
      - openssl
      - zlib
      - xz

- name: install poetry
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    name:
      - python-poetry
