- name: install go apt packages
  become: yes
  apt:
    name:
      - i3
      - rofi
      - xclip
      - rofi
      - feh
      - dex
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes
