- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link vscode config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" --no-folding {{ item }}
  with_items:
    - vscode-{{ ansible_system | lower }}
