# sourced every time

# platform dependent
if [ "$(uname)" = "Darwin" ]; then
    # hardcode homebrew prefix to speed things up
    export BREW_PREFIX="/usr/local"
    # gnu coreutils by default instead of BSD-based that macos provides
    export PATH="$BREW_PREFIX/opt/coreutils/libexec/gnubin:${PATH}"
    export MANPATH="$BREW_PREFIX/opt/coreutils/libexec/gnuman:${MANPATH}"
    # hardcode as nvim. Can't do it interactively because it will be loaded later than this script (from brew)
    export EDITOR='nvim'
fi

# lang
export LANG="en_US.UTF-8"
export LC_CTYPE="$LANG"
export LC_ALL="$LANG"

# XDG structure
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# editors and stuff
if [ -z "$EDITOR" ]; then
    if command -v nvim &>/dev/null; then
        export EDITOR='nvim'
    elif command -v vim &>/dev/null; then
        export EDITOR='vim'
    elif command -v vi &>/dev/null; then
        export EDITOR='vi'
    else
        echo "Warning! No proper editor (nvim, vim or vi) found."
    fi
fi
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"
export DIFFPROG="$EDITOR -d"

# set favorite pager
export PAGER="less -FirSwX"
export MANPAGER="less -FirSwX"

# docker buildkit feature
export DOCKER_BUILDKIT=1

# rust binaries
export PATH="$HOME/.cargo/bin:$PATH"
# go binaries
export PATH="$HOME/go/bin:$PATH"
# rancher desktop binaries
export PATH="$HOME/.rd/bin:$PATH"
# user's binaries in PATH
export PATH="$HOME/.local/bin:$PATH"
