- include: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- include: osx.yaml
  when: ansible_distribution == "MacOSX"

- include: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: link git config
  shell:
    chdir: "{{ repo_path }}/files"
    cmd: stow --target="$HOME" {{ item }}
  with_items:
    - git
    - git-{{ ansible_system | lower }}
