- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: osx.yaml
  when: ansible_distribution == "MacOSX"

- import_tasks: arch.yaml
  when: ansible_distribution == "Archlinux"

- name: enable docker daemon (dont start yet)
  become: yes
  service:
    name: docker
    state: stopped
    enabled: yes
  when:
    - ansible_system == "Linux"

- block:
    - name: Create "docker" group
      group:
        name: docker
        state: present

    - name: adding existing user "{{ target_user }}" to group "docker"
      user:
        name: "{{ target_user }}"
        groups: [docker]
        append: yes

    - name: create fake docker-compose command
      copy:
        content: |
          #!/bin/sh
          docker compose "$@"
        dest: /usr/local/bin/docker-compose

    - name: make fake docker-compose command executable
      file:
        dest: /usr/local/bin/docker-compose
        mode: a+x

  become: yes
  when:
    - ansible_system == "Linux"
