- name: Ensure this repo exists
  ansible.builtin.git:
    repo: git@github.com:konradmalik/dotfiles.git
    dest: ~/Code/dotfiles
    version: master
    recursive: "{{ 'yes' if private_machine | bool else 'no' }}"
  when: inventory_hostname != "localhost" # do this only if *not* a local machine

- name: Ensure repo exists without cloning
  file:
    path: ~/Code/dotfiles
    state: directory
