-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
-- ◌   פּ ﯟ   some other good icons

return {
    kind = {
        Text = "",
        Method = "m",
        Function = "",
        Constructor = "",
        Field = "",
        Variable = "",
        Class = "",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "",
        Enum = "",
        Keyword = "",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        EnumMember = "",
        Constant = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
    },
    type = {
        Array = "",
        Number = "",
        String = "",
        Boolean = "蘒",
        Object = "",
    },
    documents = {
        File = "",
        Files = "",
        FileContents = "",
        SymlinkFile = "",
        Folder = "",
        OpenFolder = "",
        EmptyFolder = "",
        EmptyOpenFolder = "",
        SymlinkFolder = "",
    },
    git = {
        Add = "",
        Mod = "",
        Remove = "",
        Ignore = "",
        Rename = "",
        Diff = "",
        Repo = "",
        Branch = "",
        Commit = "",
        Unmerged = "",
        Unstaged = "",
        Staged = "✓",
        Untracked = "★",
        Deleted = "✗",
    },
    ui = {
        Lock = "",
        Circle = "",
        BigCircle = "",
        BigUnfilledCircle = "",
        Square = "",
        Close = "",
        NewFile = "",
        Search = "",
        Lightbulb = "",
        Project = "",
        Dashboard = "",
        History = "",
        Comment = "",
        Bug = "",
        Code = "",
        Telescope = "",
        Gear = "",
        Gears = " ",
        Package = "",
        List = "",
        SignIn = "",
        Check = "",
        Fire = "",
        Note = "",
        BookMark = "",
        Pencil = "",
        ChevronRight = "",
        Table = "",
        Calendar = "",
        FoldClosed = "",
        FoldOpen = "",
        Animations = {
            Fill = { "  ", "_ ", "__", "▁▁", "▂▂", "▃▃", "▄▄", "▅▅", "▆▆", "▇▇", "██" },
            Dots = {
                "⠋",
                "⠙",
                "⠹",
                "⠸",
                "⠼",
                "⠴",
                "⠦",
                "⠧",
                "⠇",
                "⠏",
            },
            DotsNegative = { -- dots2
                "⣾",
                "⣽",
                "⣻",
                "⢿",
                "⡿",
                "⣟",
                "⣯",
                "⣷",
            },
            DotsSnake = { -- dots3
                "⠋",
                "⠙",
                "⠚",
                "⠒",
                "⠂",
                "⠂",
                "⠒",
                "⠲",
                "⠴",
                "⠦",
                "⠖",
                "⠒",
                "⠐",
                "⠐",
                "⠒",
                "⠓",
                "⠋",
            },
            DotsFootsteps = { -- dots10
                "⢄",
                "⢂",
                "⢁",
                "⡁",
                "⡈",
                "⡐",
                "⡠",
            },
            DotsHop = { -- dots11
                "⠁",
                "⠂",
                "⠄",
                "⡀",
                "⢀",
                "⠠",
                "⠐",
                "⠈",
            },
            Lines = {
                "-",
                "\\",
                "|",
                "/",
            },
            Pipes = {
                "┤",
                "┘",
                "┴",
                "└",
                "├",
                "┌",
                "┬",
                "┐",
            },
            DotsEllipsis = { -- simpleDots
                ".  ",
                ".. ",
                "...",
                "   ",
            },

            DotsScrolling = { -- simpleDotsScrolling
                ".  ",
                ".. ",
                "...",
                " ..",
                "  .",
                "   ",
            },
            Star = {
                "✶",
                "✸",
                "✹",
                "✺",
                "✹",
                "✷",
            },
            Flip = {
                "_",
                "_",
                "_",
                "-",
                "`",
                "`",
                "'",
                "´",
                "-",
                "_",
                "_",
                "_",
            },
            Hamburger = {
                "☱",
                "☲",
                "☴",
            },
            GrowVertical = { -- growVertical
                "▁",
                "▃",
                "▄",
                "▅",
                "▆",
                "▇",
                "▆",
                "▅",
                "▄",
                "▃",
            },
            GrowHorizontal = { -- growHorizontal
                "▏",
                "▎",
                "▍",
                "▌",
                "▋",
                "▊",
                "▉",
                "▊",
                "▋",
                "▌",
                "▍",
                "▎",
            },
            Noise = {
                "▓",
                "▒",
                "░",
            },
            DotsBounce = { -- bounce
                "⠁",
                "⠂",
                "⠄",
                "⠂",
            },
            Triangle = {
                "◢",
                "◣",
                "◤",
                "◥",
            },
            Arc = {
                "◜",
                "◠",
                "◝",
                "◞",
                "◡",
                "◟",
            },
            Circle = {
                "◡",
                "⊙",
                "◠",
            },
            SquareCorners = { -- squareCorners
                "◰",
                "◳",
                "◲",
                "◱",
            },
            CircleQuarters = { -- circleQuarters
                "◴",
                "◷",
                "◶",
                "◵",
            },
            CircleHalves = { -- circleHalves
                "◐",
                "◓",
                "◑",
                "◒",
            },
            DotsToggle = { -- toggle
                "⊶",
                "⊷",
            },
            BoxToggle = { -- toggle2
                "▫",
                "▪",
            },
            Arrow = {
                "←",
                "↖",
                "↑",
                "↗",
                "→",
                "↘",
                "↓",
                "↙",
            },
            Zip = { -- arrow3
                "▹▹▹▹▹",
                "▸▹▹▹▹",
                "▹▸▹▹▹",
                "▹▹▸▹▹",
                "▹▹▹▸▹",
                "▹▹▹▹▸",
            },
            BouncingBar = { -- bouncingBar
                "[    ]",
                "[=   ]",
                "[==  ]",
                "[=== ]",
                "[ ===]",
                "[  ==]",
                "[   =]",
                "[    ]",
                "[   =]",
                "[  ==]",
                "[ ===]",
                "[====]",
                "[=== ]",
                "[==  ]",
                "[=   ]",
            },
            BouncingBall = { -- bouncingBall
                "( ●    )",
                "(  ●   )",
                "(   ●  )",
                "(    ● )",
                "(     ●)",
                "(    ● )",
                "(   ●  )",
                "(  ●   )",
                "( ●    )",
                "(●     )",
            },
            Clock = {
                "🕛 ",
                "🕐 ",
                "🕑 ",
                "🕒 ",
                "🕓 ",
                "🕔 ",
                "🕕 ",
                "🕖 ",
                "🕗 ",
                "🕘 ",
                "🕙 ",
                "🕚 ",
            },
            Earth = {
                "🌍 ",
                "🌎 ",
                "🌏 ",
            },
            Moon = {
                "🌑 ",
                "🌒 ",
                "🌓 ",
                "🌔 ",
                "🌕 ",
                "🌖 ",
                "🌗 ",
                "🌘 ",
            },
            DotsPulse = { -- point
                "∙∙∙",
                "●∙∙",
                "∙●∙",
                "∙∙●",
                "∙∙∙",
            },
            Meter = { -- aesthetic
                "▰▱▱▱▱▱▱",
                "▰▰▱▱▱▱▱",
                "▰▰▰▱▱▱▱",
                "▰▰▰▰▱▱▱",
                "▰▰▰▰▰▱▱",
                "▰▰▰▰▰▰▱",
                "▰▰▰▰▰▰▰",
                "▰▱▱▱▱▱▱",
            },
        },
    },
    lines = {
        Corner = "└",
        Edge = "│",
    },
    diagnostics = {
        Error = "",
        Warning = "",
        Information = "",
        Question = "",
        Hint = "",
        Attention = "",
    },
    misc = {
        Robot = "ﮧ",
        Squirrel = "",
        Tag = "",
        Watch = "",
    },
}
