# restic exclude patterns: a pattern without a leading slash matches at any
# depth, "*" stays within one path component and "**" crosses any number of
# them. A directory is skipped as a whole, restic does not descend into it.
home: [
  "*.o"
  "*.pyc"
  "*.log"
  "*-shm"
  "*-wal"
  "*.sqlite-journal"
  ".DS_Store"

  "__pycache__"
  "node_modules"
  ".direnv"
  ".mypy_cache"
  ".pytest_cache"
  ".ruff_cache"
  "${home}/Code/**/bin"
  "${home}/Code/**/obj"

  "${home}/.cache"
  "${home}/.local/share"
  "${home}/.local/state"
  "${home}/Downloads"

  "${home}/.azcopy"
  "${home}/.cargo"
  "${home}/.clangd"
  "${home}/.dotnet"
  "${home}/.go"
  "${home}/.gradle"
  "${home}/.m2"
  "${home}/.npm"
  "${home}/.nuget"
  "${home}/.opam"
  "${home}/.pnpm"
  "${home}/.terraform"
  "${home}/go"

  "${home}/.config/Slack"
  "${home}/.config/syncthing/index-v2"

  "${home}/.config/**/Cache"
  "${home}/.config/**/CachedData"
  "${home}/.config/**/Code Cache"
  "${home}/.config/**/Crashpad"
  "${home}/.config/**/DawnCache"
  "${home}/.config/**/GPUCache"
  "${home}/.config/**/ShaderCache"
  "${home}/.config/**/Service Worker/CacheStorage"

  "${home}/.config/mozilla/firefox/Crash Reports"
  "${home}/.config/mozilla/firefox/Pending Pings"
  "${home}/.config/mozilla/firefox/*/crashes"
  "${home}/.config/mozilla/firefox/*/datareporting"
  "${home}/.config/mozilla/firefox/*/gmp-*"
  "${home}/.config/mozilla/firefox/*/minidumps"
  "${home}/.config/mozilla/firefox/*/saved-telemetry-pings"
  "${home}/.config/mozilla/firefox/*/security_state"
  "${home}/.config/mozilla/firefox/*/sessionstore-backups"
  "${home}/.config/mozilla/firefox/*/storage"
  "${home}/.config/mozilla/firefox/*/AlternateServices.bin"
  "${home}/.config/mozilla/firefox/*/bounce-tracking-protection.sqlite"
  "${home}/.config/mozilla/firefox/*/content-prefs.sqlite"
  "${home}/.config/mozilla/firefox/*/cookies.sqlite"
  "${home}/.config/mozilla/firefox/*/domain_to_categories.sqlite"
  "${home}/.config/mozilla/firefox/*/favicons.sqlite"
  "${home}/.config/mozilla/firefox/*/protections.sqlite"

  # authoritative copy lives on the imap server, unlike Mail/
  "${home}/.thunderbird/*/ImapMail"
  "${home}/.thunderbird/*/crashes"
  "${home}/.thunderbird/*/datareporting"
  "${home}/.thunderbird/*/minidumps"
  "${home}/.thunderbird/*/saved-telemetry-pings"
  "${home}/.thunderbird/*/global-messages-db.sqlite"
]
